config/routes.rb
Testapp::Application.routes.draw do

  resources :questions, :only => [:create, :new, :destroy] do
    member do
      get 'answer'
      post 'save_answer'
    end
    
    resources :comments, :only => [:create, :index]
  end

  match 'test' => 'questions#test'

  root :to => 'questions#index'

end

app/models/comment.rb
require 'validators/comment/question_commentable'

class Comment < ActiveRecord::Base
  belongs_to :question, :inverse_of => :comments
  
  default_scope order('created_at DESC')
  
  validates :question, :text, :presence => true
  validates_with Validators::Comment::QuestionCommentable, :if => :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  default_scope order('created_at DESC')
  
  attr_protected :answer
  
  has_many :comments, :inverse_of => :question, :dependent => :destroy
  
  validates :text, :presence => true
  validates :answer, :presence => true, :unless => :new_record?
  
  def answered?
    answer.present?
  end
  
  def commentable?
    answered?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController< ApplicationController

  before_filter :find_question, :assign_comments
  
  def index
    @comment = Comment.new :question_id => @question.id
  end
  
  def create
    @comment = Comment.new :question_id => @question.id, :text => params[:comment][:text]
    if @comment.save
      redirect_to question_comments_url(@question), notice: "Comment added"
    else
      render action: "index"
    end
  end
  
  
  private
  
  def assign_comments
    @comments = @question.comments
  end
  
  def find_question
    @question = Question.find params[:question_id]
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :find_question_by_id, :only => [:answer, :save_answer]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new params[:question]
    
    respond_to do |format|
      format.js {
        if @question.save
          render :nothing => true
        else
          render :json => @question.errors
        end
      }
      format.html {
        if @question.save
          redirect_to root_url, notice: "Question asked"
        else
          render action: "new"
        end
      }
    end      
  end

  def answer
  end

  def save_answer
    @question.answer = params[:question][:answer]

    if @question.save
      redirect_to root_url, notice: "Question answered."
    else
      render action: "answer"
    end
  end
  
  
  def test
    @questions = Question.all
  end
  
  def destroy
    Question.delete params[:id]
    render :nothing => true
  end


  private
  
  def find_question_by_id
    @question = Question.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/comments/index.html.haml
-content_for(:back) do
  %p
    =link_to "Back to questions", root_path

%h1 Question

%h2
  =@question.text

%h2 Answer
%p
  %em
    =@question.answer

=yield :back

-unless @comments.empty?
  %ul
    -@comments.each do |comment|
      %li
        =comment.text

=form_for [@question, @comment] do |f|
  =render :partial => 'shared/errors', :locals => { :object => @comment }
  %p
    =f.label :text, "Comment"
    %br
    =f.text_area :text
  =f.submit

=yield :back

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Questions
    =stylesheet_link_tag    "application"
    =javascript_include_tag "application"
    =csrf_meta_tags
  %body
    -if notice.present?
      #notice
        =notice
    =yield

app/views/questions/answer.html.haml
%h1 Answering
%h2
  =@question.text
=form_for @question, :url => save_answer_question_path(@question), :method => :post do |f|
  =render :partial => 'shared/errors', :locals => { :object => @question }
  %p
    =f.label :answer
    %br
    =f.text_area :answer
  =f.submit

%p
  =link_to 'Back', root_path

app/views/questions/index.html.haml
-content_for(:ask_new_question) do
  %p
    =link_to "Ask new question", new_question_path

%h1 Questions
-if @questions.present?
  =yield :ask_new_question
  %ul
    -@questions.each do |question|
      %li
        %h2
          -if question.answered?
            (answered)
            -if question.commentable?
              =link_to question.text, question_comments_path(question)
            -else
              =question.text
          -else
            =link_to question.text, answer_question_path(question)
  =yield :ask_new_question
-else
  %p
    No questions provided yet.
    %br
    Please,
    =link_to "ask one", new_question_path

app/views/questions/new.html.haml
%h1 Ask question
=form_for @question do |f|
  =render :partial => 'shared/errors', :locals => { :object => @question }
  %p
    =f.label :text
    %br
    =f.text_area :text
  =f.submit

%p
  =link_to 'Back', root_path

app/views/questions/test.html.haml
=javascript_include_tag 'rr.jquery.js'
=javascript_include_tag 'crud_test'

%p
  %a#create_test{ :href => '#' }
    Test create

%p
  %a#create_test_error{ :href => '#' }
    Test create error

%ul
  -@questions.each do |question|
    %li
      %h2
        =question.text
      %a.delete{ :href => '#', :resource => 'questions', :resource_id => question.id }
        Удалить

app/views/shared/_errors.html.haml
-if object.errors.any?
  %div#error_explanation
    %h2
      =pluralize object.errors.count, "error"
    %ul
      -object.errors.full_messages.each do |msg|
        %ll
          =msg